AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Dragons-sam-app

  SAM Template for creating dragons 

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: python3.11
    Layers:
      - !Ref DragonsAppDependencyLayer

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "user-pool-${Environment}"
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  DragonsApi:
    DependsOn: UserPool
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "dragons-api-${Environment}"
      StageName: DragonsAPI
      Cors: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt "UserPool.Arn"

  DragonsAppDependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: "DependencyLayer"
      Description: "Layer shared dependencies"
      ContentUri: shared_layer
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: makefile

  CreateDragonFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "CreateDragonFunction-${Environment}"
      CodeUri: create_dragon/
      Handler: create_dragon.lambda_handler
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt DragonsTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref DragonsTable
          AWS_REGION_NAME: !Ref AWS::Region
          ENV: !Ref Environment
      Events:
        Dragons:
          Type: Api
          Properties:
            Path: /dragons
            Method: post
            RestApiId: !Ref DragonsApi
            Auth:
              Authorizer: CognitoAuthorizer

  GetDragonsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "GetDragonsFunction-${Environment}"
      CodeUri: get_dragons/
      Handler: get_dragons.lambda_handler
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:Scan
            Resource: !GetAtt DragonsTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref DragonsTable
          AWS_REGION_NAME: !Ref AWS::Region
          ENV: !Ref Environment
      Events:
        Dragons:
          Type: Api
          Properties:
            Path: /dragons
            Method: get
            RestApiId: !Ref DragonsApi

  RetrieveDragonFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "RetrieveDragonFunction-${Environment}"
      CodeUri: retrieve_dragon/
      Handler: retrieve_dragon.lambda_handler
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:GetItem
            Resource: !GetAtt DragonsTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref DragonsTable
          AWS_REGION_NAME: !Ref AWS::Region
          ENV: !Ref Environment
      Events:
        Dragons:
          Type: Api
          Properties:
            Path: /dragons/{dragon_id}
            Method: get
            RestApiId: !Ref DragonsApi

  UpdateDragonFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "UpdateDragonFunction-${Environment}"
      CodeUri: update_dragon/
      Handler: update_dragon.lambda_handler
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
            Resource: !GetAtt DragonsTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref DragonsTable
          AWS_REGION_NAME: !Ref AWS::Region
          ENV: !Ref Environment
      Events:
        Dragons:
          Type: Api
          Properties:
            Path: /dragons/{dragon_id}
            Method: put
            RestApiId: !Ref DragonsApi
            Auth:
              Authorizer: CognitoAuthorizer

  DeleteDragonFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "DeleteDragonFunction-${Environment}"
      CodeUri: delete_dragon/
      Handler: delete_dragon.lambda_handler
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:DeleteItem
            Resource: !GetAtt DragonsTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref DragonsTable
          AWS_REGION_NAME: !Ref AWS::Region
          ENV: !Ref Environment
      Events:
        Dragons:
          Type: Api
          Properties:
            Path: /dragons/{dragon_id}
            Method: delete
            RestApiId: !Ref DragonsApi
            Auth:
              Authorizer: CognitoAuthorizer

  StreamHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "StreamHandlerFunction-${Environment}"
      CodeUri: stream_handler/
      Handler: stream_handler.lambda_handler
      Events:
        DDBEvent:
          Type: DynamoDB
          Properties:
            Stream:
              !GetAtt DragonsTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 1
            Enabled: true
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref DragonEventsQueue
          AWS_REGION_NAME: !Ref AWS::Region
      Policies:
        - DynamoDBStreamReadPolicy:
            TableName: !Ref DragonsTable
            StreamName: !GetAtt DragonsTable.StreamArn
        - SQSSendMessagePolicy:
            QueueName: !GetAtt DragonEventsQueue.QueueName

  SchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: send-message-to-sqs
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: !GetAtt DailyReportQueue.Arn

  DailyReportScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: DailyReportScheduler
      ScheduleExpression: cron(0 0 * * ? *)
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt DailyReportQueue.Arn
        RoleArn: !GetAtt SchedulerRole.Arn
        Input: '{"task": "daily_report_trigger"}'

  DragonEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "dragon-events-queue-${Environment}.fifo"
      FifoQueue: true
      ContentBasedDeduplication: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DragonEventsDLQ.Arn
        maxReceiveCount: 5

  DragonEventsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "dragon-events-dlq-${Environment}.fifo"
      FifoQueue: true
      ContentBasedDeduplication: true

  DailyReportQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "daily-report-queue-${Environment}"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DailyReportDLQ.Arn
        maxReceiveCount: 5

  DailyReportDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "daily-report-dlq-${Environment}"

  DragonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "dragons-${Environment}"
      AttributeDefinitions:
        - AttributeName: dragon_id
          AttributeType: S
      KeySchema:
        - AttributeName: dragon_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  DailyReportBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "daily-report-bucket-${Environment}"

Outputs:
  CreateDragonFunction:
    Description: "Lambda Function ARN for creating dragons"
    Value: !GetAtt CreateDragonFunction.Arn
  DragonsTableName:
    Description: "DynamoDB Table for storing dragons"
    Value: !Ref DragonsTable
  MyLayerVersion:
    Description: "Lambda Layer for shared dependencies"
    Value: !Ref DragonsAppDependencyLayer
