AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Dragons-sam-app

  SAM Template for creating dragons via Lambda function, DynamoDB, and Lambda Layer.

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: "DependencyLayer"
      Description: "Layer shared dependencies"
      ContentUri: .
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: makefile

  CreateDragonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: lambda_handler.create_dragon.lambda_handler
      Runtime: python3.11
      Layers:
        - !Ref MyLayer
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt DragonsTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref DragonsTable
          REGION: !Ref AWS::Region
          ENV: !Ref Environment
      Events:
        CreateDragonApi:
          Type: Api
          Properties:
            Path: /dragons
            Method: post

  DragonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "dragons-${Environment}"
      AttributeDefinitions:
        - AttributeName: dragon_id
          AttributeType: S
      KeySchema:
        - AttributeName: dragon_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  CreateDragonFunction:
    Description: "Lambda Function ARN for creating dragons"
    Value: !GetAtt CreateDragonFunction.Arn
  CreateDragonFunctionIamRole:
    Description: "Implicit IAM Role created for Create Dragon function"
    Value: !GetAtt CreateDragonFunctionRole.Arn
  DragonsTableName:
    Description: "DynamoDB Table for storing dragons"
    Value: !Ref DragonsTable
  MyLayerVersion:
    Description: "Lambda Layer for shared dependencies"
    Value: !Ref MyLayer
